import type { Metadata } from "next";
import { Geist, Geist_Mono, Montserrat, Ubuntu_Mono } from "next/font/google";
import "./globals.css";
import Header from "./layout/header";
import FloatingCart from "./Component/trending/FloatingCart";
import CartDrawer from "./Component/CartDrawer";
import { QueryClientWrapper } from "./Component/QueryClientWrapper";
import { ToastContainer } from "react-toastify";
import Marquee from "@/Component1/Marquee";
import Navbar from "@/Component1/layout/Navbar";
import MainWrapper from "./Component/MainWrapper";
import Footer from "@/Component1/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400"],
});

const ubuntuMono = Ubuntu_Mono({
  variable: "--font-ubuntu-mono",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${montserrat.variable} ${ubuntuMono.variable} antialiased`}
      >
        <QueryClientWrapper>
          <ToastContainer position="top-center" autoClose={2000} />

          {/* <Marquee /> */}
          <Navbar />
          {/* <Header /> */}
          <MainWrapper>{children}</MainWrapper>
          <CartDrawer />
          <Footer />
          {/* <Footer /> */}
        </QueryClientWrapper>
      </body>
    </html>
  );
}
