server {
    listen 80;
    server_name groceberry.com www.groceberry.com crm.groceberry.com api.groceberry.com upload.groceberry.com;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name www.groceberry.com;

    ssl_certificate /etc/letsencrypt/live/groceberry.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/groceberry.com/privkey.pem;

    location /sitemap.xml {
        proxy_pass http://127.0.0.1:4009/api/v1/website/sitemap.xml;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://127.0.0.1:3009;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Disable buffering for streaming support
        proxy_buffering off;
        proxy_set_header X-Accel-Buffering no;
    }
}

 server {
     listen 443 ssl;
     server_name groceberry.com;

     ssl_certificate /etc/letsencrypt/live/groceberry.com/fullchain.pem;
     ssl_certificate_key /etc/letsencrypt/live/groceberry.com/privkey.pem;

     location / {
         return 301 https://www.groceberry.com$request_uri;
     }
 }

server {
    listen 443 ssl;
    server_name crm.groceberry.com;

    ssl_certificate /etc/letsencrypt/live/groceberry.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/groceberry.com/privkey.pem;

    location / {
        proxy_pass http://127.0.0.1:6009;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Disable buffering for streaming support
        proxy_buffering off;
        proxy_set_header X-Accel-Buffering no;
    }
}

server {
    listen 443 ssl;
    server_name api.groceberry.com;

    client_max_body_size 10M;

    ssl_certificate /etc/letsencrypt/live/groceberry.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/groceberry.com/privkey.pem;

    location / {
        # limit_req zone=api_zone burst=30 nodelay;  # Apply rate limit here
        proxy_pass http://127.0.0.1:4009;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name upload.groceberry.com;

    client_max_body_size 200M;

    ssl_certificate /etc/letsencrypt/live/groceberry.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/groceberry.com/privkey.pem;

    location / {
        # limit_req zone=upload_zone burst=5 nodelay;  # Apply rate limit here
        proxy_pass http://127.0.0.1:5009;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}