import type { Metadata } from "next";
import { Open_Sans, Inter } from "next/font/google";
import "./globals.css";
import { Header } from "./component/Header";
import Footer from "./component/Footer";
import MobileSidebar from "./component/MobileSidebar";
import CartSideBar from "./component/CartSideBar";
import MobileSearchSidebar from "./component/MobileSearchSidebar";
import ReactQueryProvider from "./component/Providers/ReactQueryProvider";
import ToastifyProvider from "./component/Providers/ToastifyProvider";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} ${inter.variable} antialiased`}>
        <ReactQueryProvider>
          <ToastifyProvider>
            <MobileSearchSidebar />
            <MobileSidebar />
            <CartSideBar />
            <Header />
            {children}
            <Footer />
          </ToastifyProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
