import type { Metadata } from "next";
import { League_Spartan } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import SearchBar from "./components/ZustandComponents/SearchBar";
import CartSideBar from "./components/ZustandComponents/CartSideBar";
import MobileSidebar from "./components/ZustandComponents/MobileSidebar";
import MobileNavigationBar from "./components/MobileNavigationBar";
import ReactQueryProvider from "./components/ReactQueryProvider";
import ToastifyProvider from "./components/ToastifyProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const leageSpartan = League_Spartan({
  variable: "--font-leage-spartan",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${leageSpartan.variable} antialiased`}>
        <ReactQueryProvider>
          <ToastifyProvider>
            <Header />
            <SearchBar />
            <CartSideBar />
            <MobileSidebar />
            {children}
            <MobileNavigationBar />
            <Footer />
          </ToastifyProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
